CREATE DATABASE LOJACARROS;
USE LOJACARROS;

CREATE TABLE USUARIO(
ID INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOME VARCHAR(80) NOT NULL,
USERNAME VARCHAR(50)NOT NULL UNIQUE,
SENHA VARCHAR(10)NOT NULL);

CREATE TABLE CLIENTE(
ID INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOME VARCHAR(80),
nome_fantasia VARCHAR(80),
cnpj LONG,
cpf LONG,
rg LONG,
telefone VARCHAR(13),
endereco VARCHAR(80),
numero_residencia INT,
estado VARCHAR(30),
cidade VARCHAR(80),
bairro VARCHAR(80),
cep LONG,
data_nascimento DATE,
tipo VARCHAR(3));

INSERT INTO USUARIO(nome,username,senha) VALUE('victor','victor','123');
select * from CLIENTE;