/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.ProdutoController;
import br.senac.model.PessoaJuridica;
import br.senac.model.Produto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author victor.ganjos
 */
public class AtualizaProduto extends javax.swing.JFrame {

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public AtualizaProduto() {
        initComponents();
    }
    
    public AtualizaProduto(int id) {
        initComponents();
        this.id = id;
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TitlePageBackground = new javax.swing.JPanel();
        pnl_UserBackground = new javax.swing.JPanel();
        lbl_TextoInfo = new javax.swing.JLabel();
        lbl_Modelo = new javax.swing.JLabel();
        txt_Modelo = new javax.swing.JTextField();
        lbl_Ano = new javax.swing.JLabel();
        lbl_Marca = new javax.swing.JLabel();
        txt_Marca = new javax.swing.JTextField();
        lbl_TextoInfo2 = new javax.swing.JLabel();
        txt_Ano = new javax.swing.JTextField();
        txt_Placa = new javax.swing.JTextField();
        txt_Cor = new javax.swing.JTextField();
        txt_valorCompra = new javax.swing.JTextField();
        lbl_Cor = new javax.swing.JLabel();
        lbl_Placa = new javax.swing.JLabel();
        lbl_valorCompra = new javax.swing.JLabel();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        pnl_TitleUserPageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_TitlePageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_UserBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_UserBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TextoInfo.setText("Preencha os campos abaixo:");

        lbl_Modelo.setText("Modelo*");

        lbl_Ano.setText("Ano*");

        lbl_Marca.setText("Marca*");

        lbl_TextoInfo2.setText("Todos os campos com \"*\" são obrigatórios!");

        lbl_Cor.setText("Cor*");

        lbl_Placa.setText("Placa*");

        lbl_valorCompra.setText("Valor Compra*");

        javax.swing.GroupLayout pnl_UserBackgroundLayout = new javax.swing.GroupLayout(pnl_UserBackground);
        pnl_UserBackground.setLayout(pnl_UserBackgroundLayout);
        pnl_UserBackgroundLayout.setHorizontalGroup(
            pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TextoInfo)
                    .addComponent(lbl_TextoInfo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_UserBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Marca)
                                    .addComponent(lbl_Ano))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Ano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txt_Marca, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(103, 103, 103)
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                        .addComponent(lbl_Cor)
                                        .addGap(23, 23, 23)
                                        .addComponent(txt_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                        .addComponent(lbl_Placa)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_UserBackgroundLayout.createSequentialGroup()
                                .addComponent(lbl_valorCompra)
                                .addGap(18, 18, 18)
                                .addComponent(txt_valorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbl_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        pnl_UserBackgroundLayout.setVerticalGroup(
            pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TextoInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Modelo))
                .addGap(18, 18, 18)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Marca)
                    .addComponent(txt_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cor))
                .addGap(18, 18, 18)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Ano)
                    .addComponent(txt_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Placa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valorCompra))
                .addGap(28, 28, 28))
        );

        btn_Salvar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Salvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Limpar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Limpar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TitlePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitlePageBackground);
        pnl_TitlePageBackground.setLayout(pnl_TitlePageBackgroundLayout);
        pnl_TitlePageBackgroundLayout.setHorizontalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(pnl_UserBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_TitlePageBackgroundLayout.setVerticalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_UserBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_TitleUserPageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleUserPageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleUserPageBackground);
        pnl_TitleUserPageBackground.setLayout(pnl_TitleUserPageBackgroundLayout);
        pnl_TitleUserPageBackgroundLayout.setHorizontalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleUserPageBackgroundLayout.setVerticalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void load() {
        List<Produto> lista = ProdutoController.consultarPorId(id);
        for (Produto li : lista) {
            
            txt_Modelo.setText(li.getModelo());
            txt_Marca.setText(li.getMarca());
            txt_Ano.setText(li.getAno());
            txt_Cor.setText(li.getCor());
            txt_Placa.setText(li.getPlaca());
            txt_valorCompra.setText(String.valueOf(li.getValorCompra()));
        }
    }
    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        ProdutoController control = new ProdutoController();
        String modelo = txt_Modelo.getText();
        String marca = txt_Marca.getText();
        String ano = txt_Ano.getText();
        String cor = txt_Cor.getText();
        String placa = txt_Placa.getText();
        Double valorCompra = Double.parseDouble(txt_valorCompra.getText());

        if (modelo.equals("") || marca.equals("") || ano.equals("") || cor.equals("") || placa.equals("") || valorCompra.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            control.atualizar(id, modelo, marca, ano, cor, placa, valorCompra);
            JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!");
            HomePage home = new HomePage();
            home.setVisible(true);
            AtualizaProduto.this.dispose();
        }

    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        int logout = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Cancelar?");
        System.out.println(logout);
        if (logout == 0) {
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada!");
            HomePage home = new HomePage();
            home.setVisible(true);
            AtualizaProduto.this.dispose();
        }
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        txt_Modelo.setText("");
        txt_Marca.setText("");
        txt_Ano.setText("");
        txt_Cor.setText("");
        txt_Placa.setText("");
        txt_valorCompra.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel lbl_Ano;
    private javax.swing.JLabel lbl_Cor;
    private javax.swing.JLabel lbl_Marca;
    private javax.swing.JLabel lbl_Modelo;
    private javax.swing.JLabel lbl_Placa;
    private javax.swing.JLabel lbl_TextoInfo;
    private javax.swing.JLabel lbl_TextoInfo2;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_valorCompra;
    private javax.swing.JPanel pnl_TitlePageBackground;
    private javax.swing.JPanel pnl_TitleUserPageBackground;
    private javax.swing.JPanel pnl_UserBackground;
    private javax.swing.JTextField txt_Ano;
    private javax.swing.JTextField txt_Cor;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_Modelo;
    private javax.swing.JTextField txt_Placa;
    private javax.swing.JTextField txt_valorCompra;
    // End of variables declaration//GEN-END:variables
}
