/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.PessoaFisicaController;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author victor.ganjos
 */
public class CadastroPF extends javax.swing.JFrame {

    public CadastroPF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TitlePageBackground = new javax.swing.JPanel();
        pnl_ClienteBackground = new javax.swing.JPanel();
        lbl_TextoInfo = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lxl_CPF = new javax.swing.JLabel();
        txt_CPF = new javax.swing.JTextField();
        lbl_RG = new javax.swing.JLabel();
        txt_RG = new javax.swing.JTextField();
        lbl_DataNasc = new javax.swing.JLabel();
        txt_DataNasc = new javax.swing.JTextField();
        lbl_Endereco = new javax.swing.JLabel();
        txt_Endereco = new javax.swing.JTextField();
        lbl_Telefone = new javax.swing.JLabel();
        txt_Telefone = new javax.swing.JTextField();
        lbl_Numero = new javax.swing.JLabel();
        txt_NumeroEnd = new javax.swing.JTextField();
        lbl_UF = new javax.swing.JLabel();
        lbl_Cidade = new javax.swing.JLabel();
        txt_Cidade = new javax.swing.JTextField();
        cbo_UF = new javax.swing.JComboBox<>();
        lbl_Bairro = new javax.swing.JLabel();
        txt_Bairro = new javax.swing.JTextField();
        lbl_CEP = new javax.swing.JLabel();
        txt_CEP = new javax.swing.JTextField();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        pnl_TitleClientePageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_TitlePageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_ClienteBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ClienteBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TextoInfo.setText("Preencha os campos abaixo:");

        lbl_Nome.setText("Nome Completo*");

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        lxl_CPF.setText("CPF*");

        lbl_RG.setText("RG*");

        lbl_DataNasc.setText("Data de Nascimento*");

        txt_DataNasc.setText("EX: 1990-01-20");
        txt_DataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataNascActionPerformed(evt);
            }
        });

        lbl_Endereco.setText("Endereço*");

        lbl_Telefone.setText("Telefone*");

        lbl_Numero.setText("Nº*");

        lbl_UF.setText("Estado-(UF)*");

        lbl_Cidade.setText("Cidade*");

        cbo_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lbl_Bairro.setText("Bairro");

        lbl_CEP.setText("CEP*");

        javax.swing.GroupLayout pnl_ClienteBackgroundLayout = new javax.swing.GroupLayout(pnl_ClienteBackground);
        pnl_ClienteBackground.setLayout(pnl_ClienteBackgroundLayout);
        pnl_ClienteBackgroundLayout.setHorizontalGroup(
            pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                        .addComponent(lbl_Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NumeroEnd))
                    .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                        .addComponent(lbl_UF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Cidade))
                    .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_TextoInfo)
                        .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                            .addComponent(lbl_Nome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Nome))
                        .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                            .addComponent(lxl_CPF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_RG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                            .addComponent(lbl_DataNasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_Telefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Telefone)))
                    .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                        .addComponent(lbl_Bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_CEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_CEP)))
                .addContainerGap())
        );
        pnl_ClienteBackgroundLayout.setVerticalGroup(
            pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lxl_CPF))
                    .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_RG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ClienteBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DataNasc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Endereco)
                            .addComponent(txt_NumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Numero)))
                    .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Telefone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UF)
                    .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cidade)
                    .addComponent(cbo_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ClienteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Bairro)
                    .addComponent(txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CEP))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        btn_Salvar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Salvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Limpar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Limpar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TitlePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitlePageBackground);
        pnl_TitlePageBackground.setLayout(pnl_TitlePageBackgroundLayout);
        pnl_TitlePageBackgroundLayout.setHorizontalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(pnl_ClienteBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_TitlePageBackgroundLayout.setVerticalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ClienteBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_TitleClientePageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleClientePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleClientePageBackground);
        pnl_TitleClientePageBackground.setLayout(pnl_TitleClientePageBackgroundLayout);
        pnl_TitleClientePageBackgroundLayout.setHorizontalGroup(
            pnl_TitleClientePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleClientePageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleClientePageBackgroundLayout.setVerticalGroup(
            pnl_TitleClientePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleClientePageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleClientePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleClientePageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        PessoaFisicaController control = new PessoaFisicaController();;
        String nome = txt_Nome.getText();
        String cpf = txt_CPF.getText();
        String rg = txt_RG.getText();
        String dataNasc = txt_DataNasc.getText();
        String telefone = txt_Telefone.getText();
        String endereco = txt_Endereco.getText();
        String numero = txt_NumeroEnd.getText();
        String uf = cbo_UF.getSelectedItem().toString();
        String cidade = txt_Cidade.getText();
        String bairro = txt_Bairro.getText();
        String cep = txt_CEP.getText();

        if (nome.equals("") || cpf.equals("") || rg.equals("") || dataNasc.equals("")
                || telefone.equals("") || endereco.equals("") || numero.equals("")
                || uf.equals("") || cidade.equals("") || cep.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");

        } else {
            control.salvar(Long.parseLong(cpf), Long.parseLong(rg), Date.valueOf(dataNasc), Integer.parseInt(numero), nome, endereco, bairro, cidade, uf, telefone, Long.parseLong(cep));
            JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!");
            HomePage home = new HomePage();
            home.setVisible(true);
            CadastroPF.this.dispose();
        }

    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        int logout = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Cancelar?");
        System.out.println(logout);
        if (logout == 0) {
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada!");
            HomePage home = new HomePage();
            home.setVisible(true);
            CadastroPF.this.dispose();
        }
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        txt_Nome.setText("");
        txt_CPF.setText("");
        txt_RG.setText("");
        txt_DataNasc.setText("");
        txt_Telefone.setText("");
        txt_Endereco.setText("");
        txt_NumeroEnd.setText("");
        txt_Cidade.setText("");
        txt_Bairro.setText("");
        txt_CEP.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void txt_DataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataNascActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JComboBox<String> cbo_UF;
    private javax.swing.JLabel lbl_Bairro;
    private javax.swing.JLabel lbl_CEP;
    private javax.swing.JLabel lbl_Cidade;
    private javax.swing.JLabel lbl_DataNasc;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Numero;
    private javax.swing.JLabel lbl_RG;
    private javax.swing.JLabel lbl_Telefone;
    private javax.swing.JLabel lbl_TextoInfo;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_UF;
    private javax.swing.JLabel lxl_CPF;
    private javax.swing.JPanel pnl_ClienteBackground;
    private javax.swing.JPanel pnl_TitleClientePageBackground;
    private javax.swing.JPanel pnl_TitlePageBackground;
    private javax.swing.JTextField txt_Bairro;
    private javax.swing.JTextField txt_CEP;
    private javax.swing.JTextField txt_CPF;
    private javax.swing.JTextField txt_Cidade;
    private javax.swing.JTextField txt_DataNasc;
    private javax.swing.JTextField txt_Endereco;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_NumeroEnd;
    private javax.swing.JTextField txt_RG;
    private javax.swing.JTextField txt_Telefone;
    // End of variables declaration//GEN-END:variables
}
