/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.UsuarioController;
import br.senac.repository.Table;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor.ganjos
 */
public class ConsultaUsuario extends javax.swing.JFrame implements Table{

    public ConsultaUsuario() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public void loadTable() {
        ArrayList<String[]> linhasUsuarios = UsuarioController.consulta();
        DefaultTableModel tmUsuarios = new DefaultTableModel();
        tmUsuarios.addColumn("ID");
        tmUsuarios.addColumn("NOME");
        tmUsuarios.addColumn("USERNAME");
        tbl_ConsultaUsuario.setModel(tmUsuarios);
        for (String[] c : linhasUsuarios) {
            tmUsuarios.addRow(c);
        }
        tbl_ConsultaUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbl_ConsultaUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_ConsultaUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
    }

    public void pesquisar() {
        ArrayList<String[]> linhasUsuarios = UsuarioController.consultaPorNome(txt_NomeUsuario.getText());

        DefaultTableModel tmUsuarios = new DefaultTableModel();
        tmUsuarios.addColumn("ID");
        tmUsuarios.addColumn("NOME");
        tmUsuarios.addColumn("USERNAME");
        tbl_ConsultaUsuario.setModel(tmUsuarios);

        for (String[] c : linhasUsuarios) {
            tmUsuarios.addRow(c);
        }

        tbl_ConsultaUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbl_ConsultaUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_ConsultaUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ConsultaUsuario = new javax.swing.JPanel();
        scp_ConsultaUsuario = new javax.swing.JScrollPane();
        tbl_ConsultaUsuario = new javax.swing.JTable();
        lbl_NomeUsuario = new javax.swing.JLabel();
        txt_NomeUsuario = new javax.swing.JTextField();
        btn_BuscarNomeUsuario = new javax.swing.JButton();
        btn_HomePage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnl_TitleClientePageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_ConsultaUsuario.setBackground(new java.awt.Color(255, 255, 255));

        tbl_ConsultaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scp_ConsultaUsuario.setViewportView(tbl_ConsultaUsuario);

        lbl_NomeUsuario.setText("Username:");

        txt_NomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeUsuarioActionPerformed(evt);
            }
        });

        btn_BuscarNomeUsuario.setText("Buscar");
        btn_BuscarNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarNomeUsuarioActionPerformed(evt);
            }
        });

        btn_HomePage.setText("Home");
        btn_HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomePageActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ConsultaUsuarioLayout = new javax.swing.GroupLayout(pnl_ConsultaUsuario);
        pnl_ConsultaUsuario.setLayout(pnl_ConsultaUsuarioLayout);
        pnl_ConsultaUsuarioLayout.setHorizontalGroup(
            pnl_ConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConsultaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scp_ConsultaUsuario)
                    .addGroup(pnl_ConsultaUsuarioLayout.createSequentialGroup()
                        .addComponent(lbl_NomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BuscarNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnl_ConsultaUsuarioLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ConsultaUsuarioLayout.setVerticalGroup(
            pnl_ConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConsultaUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_ConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NomeUsuario)
                    .addComponent(txt_NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarNomeUsuario)
                    .addComponent(btn_HomePage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scp_ConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnl_TitleClientePageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleClientePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleClientePageBackground);
        pnl_TitleClientePageBackground.setLayout(pnl_TitleClientePageBackgroundLayout);
        pnl_TitleClientePageBackgroundLayout.setHorizontalGroup(
            pnl_TitleClientePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleClientePageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleClientePageBackgroundLayout.setVerticalGroup(
            pnl_TitleClientePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleClientePageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_ConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleClientePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleClientePageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeUsuarioActionPerformed

    private void btn_BuscarNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarNomeUsuarioActionPerformed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_btn_BuscarNomeUsuarioActionPerformed

    private void btn_HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomePageActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        ConsultaUsuario.this.dispose();
    }//GEN-LAST:event_btn_HomePageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tbl_ConsultaUsuario.getSelectedRow() != -1) {
            //  List<PessoaFisica> linhasClientes = PessoaFisicaController.consultarPorId((int) tbl_ConsultaPF.getValueAt(tbl_ConsultaPF.getSelectedRow(), 0));
            AtualizaUsuario atualiza = new AtualizaUsuario(Integer.parseInt((String) tbl_ConsultaUsuario.getValueAt(tbl_ConsultaUsuario.getSelectedRow(), 0)));
            atualiza.setVisible(true);
            ConsultaUsuario.this.dispose();

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tbl_ConsultaUsuario.getSelectedRow() != -1) {

            UsuarioController.excluir(Integer.parseInt((String) tbl_ConsultaUsuario.getValueAt(tbl_ConsultaUsuario.getSelectedRow(), 0)));
            loadTable();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarNomeUsuario;
    private javax.swing.JButton btn_HomePage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl_NomeUsuario;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JPanel pnl_ConsultaUsuario;
    private javax.swing.JPanel pnl_TitleClientePageBackground;
    private javax.swing.JScrollPane scp_ConsultaUsuario;
    private javax.swing.JTable tbl_ConsultaUsuario;
    private javax.swing.JTextField txt_NomeUsuario;
    // End of variables declaration//GEN-END:variables
}
