/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.UsuarioController;
import br.senac.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author victor.ganjos
 */
public class LoginPage extends javax.swing.JFrame {
    
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_LoginPageBackground = new javax.swing.JPanel();
        pnl_LoginBackground = new javax.swing.JPanel();
        lbl_TitlePassword = new javax.swing.JLabel();
        lbl_TitleLogin = new javax.swing.JLabel();
        lbl_TitleUsername = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        btn_Entrar = new javax.swing.JButton();
        pwd_Password = new javax.swing.JPasswordField();
        pnl_TitleLoginPageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_LoginPageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_LoginBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_LoginBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TitlePassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_TitlePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TitlePassword.setText("Senha:");

        lbl_TitleLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_TitleLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TitleLogin.setText("Entre com os seus dados de acesso");

        lbl_TitleUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_TitleUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TitleUsername.setText("Usuário:");

        txt_Username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });

        btn_Entrar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Entrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Entrar.setText("Entrar");
        btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LoginBackgroundLayout = new javax.swing.GroupLayout(pnl_LoginBackground);
        pnl_LoginBackground.setLayout(pnl_LoginBackgroundLayout);
        pnl_LoginBackgroundLayout.setHorizontalGroup(
            pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LoginBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TitleLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addGroup(pnl_LoginBackgroundLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginBackgroundLayout.createSequentialGroup()
                                        .addComponent(lbl_TitleUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(pnl_LoginBackgroundLayout.createSequentialGroup()
                                        .addComponent(lbl_TitlePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pwd_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                    .addComponent(txt_Username))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
        );
        pnl_LoginBackgroundLayout.setVerticalGroup(
            pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TitleLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TitleUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnl_LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TitlePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout pnl_LoginPageBackgroundLayout = new javax.swing.GroupLayout(pnl_LoginPageBackground);
        pnl_LoginPageBackground.setLayout(pnl_LoginPageBackgroundLayout);
        pnl_LoginPageBackgroundLayout.setHorizontalGroup(
            pnl_LoginPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginPageBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_LoginBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_LoginPageBackgroundLayout.setVerticalGroup(
            pnl_LoginPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginPageBackgroundLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(pnl_LoginBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pnl_TitleLoginPageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleLoginPageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleLoginPageBackground);
        pnl_TitleLoginPageBackground.setLayout(pnl_TitleLoginPageBackgroundLayout);
        pnl_TitleLoginPageBackgroundLayout.setHorizontalGroup(
            pnl_TitleLoginPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleLoginPageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        pnl_TitleLoginPageBackgroundLayout.setVerticalGroup(
            pnl_TitleLoginPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleLoginPageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitleLoginPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_LoginPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleLoginPageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_LoginPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarActionPerformed
        String user = txt_Username.getText();
        String password = pwd_Password.getText();
        UsuarioController usuario = new UsuarioController();
        
        if(user.equals("")||password.equals("")){
        JOptionPane.showMessageDialog(null, "Preencha ambos os campos!");
            txt_Username.setText("");
            pwd_Password.setText("");
        }else if (usuario.consultarPorUsername(user, password)) {
 
            HomePage homePage = new HomePage();
            homePage.setVisible(true);
            LoginPage.this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos!");
            txt_Username.setText("");
            pwd_Password.setText("");
        }


    }//GEN-LAST:event_btn_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JLabel lbl_TitleLogin;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_TitlePassword;
    private javax.swing.JLabel lbl_TitleUsername;
    private javax.swing.JPanel pnl_LoginBackground;
    private javax.swing.JPanel pnl_LoginPageBackground;
    private javax.swing.JPanel pnl_TitleLoginPageBackground;
    private javax.swing.JPasswordField pwd_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
