/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.ProdutoController;
import br.senac.controller.RelatorioController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laay.dias
 */
public class RelatorioView extends javax.swing.JFrame {

    public RelatorioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @param dataInicio
     * @param dataFim
     * @throws java.text.ParseException
     */
    public void loadTableRealatorios(String dataInicio, String dataFim) throws ParseException {
        ArrayList<String[]> listaRelatorio = RelatorioController.read(dataInicio, dataFim);

        DefaultTableModel tbRelatorio = new DefaultTableModel();

        tbRelatorio.addColumn("ID VENDA");
        tbRelatorio.addColumn("Cliente");
        tbRelatorio.addColumn("Valor Total");
        tbl_TabelaRelatorio.setModel(tbRelatorio);

        for (String[] c : listaRelatorio) {
            tbRelatorio.addRow(c);
        }

        tbl_TabelaRelatorio.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbl_TabelaRelatorio.getColumnModel().getColumn(1).setPreferredWidth(80);
        tbl_TabelaRelatorio.getColumnModel().getColumn(2).setPreferredWidth(100);

    }
    
    public void loadTableRelatorio(int id) {

        ArrayList<String[]> listaVendas = ProdutoController.read2(id);

        DefaultTableModel tbItemVenda = new DefaultTableModel();

        tbItemVenda.addColumn("ID Produto");
        tbItemVenda.addColumn("Modelo");
        tbItemVenda.addColumn("Valor Unit.");
        tbl_TabelaRelatorioItensVenda.setModel(tbItemVenda);

        for (String[] c : listaVendas) {
            tbItemVenda.addRow(c);
        }

        tbl_TabelaRelatorioItensVenda.getColumnModel().getColumn(0).setPreferredWidth(80); //ID
        tbl_TabelaRelatorioItensVenda.getColumnModel().getColumn(1).setPreferredWidth(80); //ID
        tbl_TabelaRelatorioItensVenda.getColumnModel().getColumn(2).setPreferredWidth(100);

    }

    private void valoresRelatorio() {
        double auxValorTotal = 0.0;
        for (int i = 0; i < tbl_TabelaRelatorio.getRowCount(); i++) {
            auxValorTotal += Double.parseDouble(tbl_TabelaRelatorio.getValueAt(i, 2).toString());
        }
        txt_ValorTotalItensPeriodo.setText(String.valueOf(auxValorTotal));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TitlePageBackground = new javax.swing.JPanel();
        pnl_VendaBackground = new javax.swing.JPanel();
        lbl_TextoInfo = new javax.swing.JLabel();
        lbl_NomeClienteVenda = new javax.swing.JLabel();
        scp_TabelaRelatorio = new javax.swing.JScrollPane();
        tbl_TabelaRelatorio = new javax.swing.JTable();
        pnl_BuscaRelatorio = new javax.swing.JPanel();
        btn_BuscarRealtorio = new javax.swing.JButton();
        lbl_DataInicioRelatorio = new javax.swing.JLabel();
        lbl_DataFimRelatorio = new javax.swing.JLabel();
        txt_DataInicio = new javax.swing.JFormattedTextField();
        txt_DataFim = new javax.swing.JFormattedTextField();
        lbl_ValorTotalItensPeriodo = new javax.swing.JLabel();
        txt_ValorTotalItensPeriodo = new javax.swing.JTextField();
        btn_home = new javax.swing.JButton();
        btn_DetalharRelatorio = new javax.swing.JButton();
        txt_DetalharRelatorio = new javax.swing.JTextField();
        scp_TabelaRelatorioItensVenda = new javax.swing.JScrollPane();
        tbl_TabelaRelatorioItensVenda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnl_TitleUserPageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_TitlePageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_VendaBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_VendaBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TextoInfo.setText("Preencha os campos abaixo:");

        tbl_TabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venda", "Cliente", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TabelaRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TabelaRelatorioMouseClicked(evt);
            }
        });
        scp_TabelaRelatorio.setViewportView(tbl_TabelaRelatorio);

        pnl_BuscaRelatorio.setBackground(new java.awt.Color(233, 233, 233));
        pnl_BuscaRelatorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_BuscarRealtorio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_BuscarRealtorio.setText("Buscar");
        btn_BuscarRealtorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarRealtorioActionPerformed(evt);
            }
        });
        pnl_BuscaRelatorio.add(btn_BuscarRealtorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lbl_DataInicioRelatorio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_DataInicioRelatorio.setText("Data de Início");
        pnl_BuscaRelatorio.add(lbl_DataInicioRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 112, -1));

        lbl_DataFimRelatorio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_DataFimRelatorio.setText("Data de Final");
        pnl_BuscaRelatorio.add(lbl_DataFimRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 112, -1));

        try {
            txt_DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnl_BuscaRelatorio.add(txt_DataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        try {
            txt_DataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_DataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataFimActionPerformed(evt);
            }
        });
        pnl_BuscaRelatorio.add(txt_DataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        lbl_ValorTotalItensPeriodo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_ValorTotalItensPeriodo.setText("Valor total dos itens no período");
        pnl_BuscaRelatorio.add(lbl_ValorTotalItensPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        pnl_BuscaRelatorio.add(txt_ValorTotalItensPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pnl_BuscaRelatorio.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 80, -1));

        btn_DetalharRelatorio.setText("Detalhar");
        btn_DetalharRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DetalharRelatorioActionPerformed(evt);
            }
        });
        pnl_BuscaRelatorio.add(btn_DetalharRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 25));

        txt_DetalharRelatorio.setEnabled(false);
        pnl_BuscaRelatorio.add(txt_DetalharRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 25));

        tbl_TabelaRelatorioItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scp_TabelaRelatorioItensVenda.setViewportView(tbl_TabelaRelatorioItensVenda);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Detalhes Itens Venda");

        javax.swing.GroupLayout pnl_VendaBackgroundLayout = new javax.swing.GroupLayout(pnl_VendaBackground);
        pnl_VendaBackground.setLayout(pnl_VendaBackgroundLayout);
        pnl_VendaBackgroundLayout.setHorizontalGroup(
            pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_NomeClienteVenda)
                .addGap(18, 18, 18)
                .addComponent(pnl_BuscaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scp_TabelaRelatorioItensVenda)
                            .addComponent(scp_TabelaRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(179, 179, 179))))
        );
        pnl_VendaBackgroundLayout.setVerticalGroup(
            pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbl_NomeClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(pnl_BuscaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(scp_TabelaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scp_TabelaRelatorioItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout pnl_TitlePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitlePageBackground);
        pnl_TitlePageBackground.setLayout(pnl_TitlePageBackgroundLayout);
        pnl_TitlePageBackgroundLayout.setHorizontalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnl_VendaBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnl_TitlePageBackgroundLayout.setVerticalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnl_VendaBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnl_TitleUserPageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleUserPageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleUserPageBackground);
        pnl_TitleUserPageBackground.setLayout(pnl_TitleUserPageBackgroundLayout);
        pnl_TitleUserPageBackgroundLayout.setHorizontalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleUserPageBackgroundLayout.setVerticalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarRealtorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarRealtorioActionPerformed

        String dataInicio = String.valueOf(txt_DataInicio.getText());
        String dataFim = String.valueOf(txt_DataFim.getText());

        try {
            loadTableRealatorios(dataInicio, dataFim);
            valoresRelatorio();
        } catch (ParseException ex) {
            Logger.getLogger(RelatorioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarRealtorioActionPerformed

    private void txt_DataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataFimActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        RelatorioView.this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_DetalharRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DetalharRelatorioActionPerformed
        this.loadTableRelatorio(Integer.parseInt(txt_DetalharRelatorio.getText()));
    }//GEN-LAST:event_btn_DetalharRelatorioActionPerformed

    private void tbl_TabelaRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TabelaRelatorioMouseClicked
        if (tbl_TabelaRelatorio.getSelectedRow() != -1) {

            txt_DetalharRelatorio.setText(tbl_TabelaRelatorio.getValueAt(tbl_TabelaRelatorio.getSelectedRow(), 0).toString());

        }
    }//GEN-LAST:event_tbl_TabelaRelatorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarRealtorio;
    private javax.swing.JButton btn_DetalharRelatorio;
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_DataFimRelatorio;
    private javax.swing.JLabel lbl_DataInicioRelatorio;
    private javax.swing.JLabel lbl_NomeClienteVenda;
    private javax.swing.JLabel lbl_TextoInfo;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_ValorTotalItensPeriodo;
    private javax.swing.JPanel pnl_BuscaRelatorio;
    private javax.swing.JPanel pnl_TitlePageBackground;
    private javax.swing.JPanel pnl_TitleUserPageBackground;
    private javax.swing.JPanel pnl_VendaBackground;
    private javax.swing.JScrollPane scp_TabelaRelatorio;
    private javax.swing.JScrollPane scp_TabelaRelatorioItensVenda;
    private javax.swing.JTable tbl_TabelaRelatorio;
    private javax.swing.JTable tbl_TabelaRelatorioItensVenda;
    private javax.swing.JFormattedTextField txt_DataFim;
    private javax.swing.JFormattedTextField txt_DataInicio;
    private javax.swing.JTextField txt_DetalharRelatorio;
    private javax.swing.JTextField txt_ValorTotalItensPeriodo;
    // End of variables declaration//GEN-END:variables
public String dataFormato(String data) throws ParseException {

        SimpleDateFormat formatadorDatas = new SimpleDateFormat("dd/MM/yyyy");
        Date d = formatadorDatas.parse(data);
        formatadorDatas = new SimpleDateFormat("yyyy-MM-dd");
        String novaData = formatadorDatas.format(d);
        return novaData;
    }
}
