/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.ItemVendaController;
import br.senac.controller.PedidoController;
import br.senac.controller.PessoaJuridicaController;
import br.senac.controller.ProdutoController;
import br.senac.controller.VendaController;
import br.senac.dao.ProdutoDAO;
import br.senac.model.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laay.dias
 */
public class VendaJuridica extends javax.swing.JFrame {

    public VendaJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TitlePageBackground = new javax.swing.JPanel();
        pnl_VendaBackground = new javax.swing.JPanel();
        lbl_TextoInfo = new javax.swing.JLabel();
        lbl_valorTotal = new javax.swing.JLabel();
        txt_ClientePf = new javax.swing.JTextField();
        txt_Produto = new javax.swing.JTextField();
        lbl_ClientePfPj = new javax.swing.JLabel();
        lbl_Produto = new javax.swing.JLabel();
        btn_BuscarCliente = new javax.swing.JButton();
        lbl_Cliente1 = new javax.swing.JLabel();
        lbl_NomeClienteVenda = new javax.swing.JLabel();
        btn_BuscarProduto = new javax.swing.JButton();
        lbl_ValorUnitario = new javax.swing.JLabel();
        txt_ValorUnitario = new javax.swing.JTextField();
        scp_ItemVenda = new javax.swing.JScrollPane();
        tbl_ItemVenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_IdProduto = new javax.swing.JLabel();
        txt_Modelo = new javax.swing.JTextField();
        txt_Marca = new javax.swing.JTextField();
        txt_Ano = new javax.swing.JTextField();
        txt_Cor = new javax.swing.JTextField();
        txt_IdProduto = new javax.swing.JTextField();
        btn_Remover = new javax.swing.JButton();
        lbl_valorTotalSet = new javax.swing.JLabel();
        btn_Adicionar = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        pnl_TitleUserPageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_TitlePageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_VendaBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_VendaBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TextoInfo.setText("Preencha os campos abaixo:");

        lbl_valorTotal.setText("Valor total");

        lbl_ClientePfPj.setText("CNPJ");

        lbl_Produto.setText("Placa");

        btn_BuscarCliente.setText("Buscar");
        btn_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarClienteActionPerformed(evt);
            }
        });

        lbl_Cliente1.setText("Cliente:");

        btn_BuscarProduto.setText("Buscar");
        btn_BuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarProdutoActionPerformed(evt);
            }
        });

        lbl_ValorUnitario.setText("Valor Unit");

        tbl_ItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Ano", "Cor", "Placa", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scp_ItemVenda.setViewportView(tbl_ItemVenda);

        jLabel1.setText("Modelo");

        jLabel2.setText("Marca");

        jLabel3.setText("Ano");

        jLabel4.setText("Cor");

        lbl_IdProduto.setText("Id");

        txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MarcaActionPerformed(evt);
            }
        });

        txt_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AnoActionPerformed(evt);
            }
        });

        btn_Remover.setText("Remover Produto");
        btn_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoverActionPerformed(evt);
            }
        });

        btn_Adicionar.setText("Adicionar Produto");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_VendaBackgroundLayout = new javax.swing.GroupLayout(pnl_VendaBackground);
        pnl_VendaBackground.setLayout(pnl_VendaBackgroundLayout);
        pnl_VendaBackgroundLayout.setHorizontalGroup(
            pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createSequentialGroup()
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_ClientePfPj, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(lbl_Produto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lbl_IdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_IdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                                    .addComponent(txt_Produto))
                                                .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addComponent(txt_ClientePf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_BuscarCliente))))
                                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addComponent(lbl_Cliente1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_NomeClienteVenda))
                                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addGap(250, 250, 250)
                                                .addComponent(btn_BuscarProduto)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_VendaBackgroundLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(lbl_ValorUnitario)
                                            .addComponent(lbl_valorTotal))
                                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(txt_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lbl_valorTotalSet, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(59, 59, 59))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Remover)
                        .addGap(46, 46, 46)))
                .addComponent(scp_ItemVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_VendaBackgroundLayout.setVerticalGroup(
            pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ClientePfPj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_ClientePf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_BuscarCliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NomeClienteVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_BuscarProduto))
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_IdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_IdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ValorUnitario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valorTotalSet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(pnl_VendaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Remover)
                            .addComponent(btn_Adicionar))
                        .addGap(37, 37, 37))
                    .addGroup(pnl_VendaBackgroundLayout.createSequentialGroup()
                        .addComponent(scp_ItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        btn_Salvar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Salvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Limpar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Limpar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TitlePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitlePageBackground);
        pnl_TitlePageBackground.setLayout(pnl_TitlePageBackgroundLayout);
        pnl_TitlePageBackgroundLayout.setHorizontalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnl_VendaBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnl_TitlePageBackgroundLayout.setVerticalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnl_VendaBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_TitleUserPageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleUserPageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleUserPageBackground);
        pnl_TitleUserPageBackground.setLayout(pnl_TitleUserPageBackgroundLayout);
        pnl_TitleUserPageBackgroundLayout.setHorizontalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleUserPageBackgroundLayout.setVerticalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LoadTableItemVenda(String placa) {

        ArrayList<String[]> lista = ProdutoController.consultaPorPlaca(txt_Produto.getText());
        DefaultTableModel tmProduto = new DefaultTableModel();
        tmProduto.addColumn("ID");
        tmProduto.addColumn("Modelo");
        tmProduto.addColumn("Marca");
        tmProduto.addColumn("Ano");
        tmProduto.addColumn("Cor");
        tmProduto.addColumn("Placa");
        tmProduto.addColumn("Valor");
        tbl_ItemVenda.setModel(tmProduto);
        for (String[] c : lista) {
            tmProduto.addRow(c);
        }
        tbl_ItemVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_ItemVenda.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbl_ItemVenda.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(5).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(6).setPreferredWidth(50);
    }
    public void LimparFormulario() {
        txt_Produto.setText("");
        txt_IdProduto.setText("");
        txt_Marca.setText("");
        txt_Modelo.setText("");
        txt_Ano.setText("");
        txt_Cor.setText("");
        txt_ValorUnitario.setText("");
    }
    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        VendaController vendaControl = new VendaController();
        ItemVendaController itemControl = new ItemVendaController();
        PedidoController pedidoControl = new PedidoController();
        PessoaJuridicaController clientepf = new PessoaJuridicaController();
        int pj = clientepf.consultarPorCPF(Long.parseLong(txt_ClientePf.getText()));
        vendaControl.salvar(pj, Double.parseDouble(lbl_valorTotalSet.getText()));
        ProdutoController prod2 = new ProdutoController();
        for (int i = 0; i < tbl_ItemVenda.getRowCount(); i++) {
            pedidoControl.salvar(vendaControl.consultarID(), Integer.parseInt(tbl_ItemVenda.getValueAt(i, 0).toString()), Double.parseDouble(tbl_ItemVenda.getValueAt(i, 6).toString()));
        }
        for (int j = 0; j < tbl_ItemVenda.getRowCount(); j++){
            prod2.desativar(Integer.parseInt(tbl_ItemVenda.getValueAt(j, 0).toString()));
        }
        JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!");
        HomePage home = new HomePage();
        home.setVisible(true);
        VendaJuridica.this.dispose();


    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        int logout = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Cancelar?");
        System.out.println(logout);
        if (logout == 0) {
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada!");
            HomePage home = new HomePage();
            home.setVisible(true);
            VendaJuridica.this.dispose();
        }
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        lbl_valorTotalSet.setText("");
        txt_Produto.setText("");
        lbl_NomeClienteVenda.setText("");
        txt_IdProduto.setText("");
        txt_Modelo.setText("");
        txt_Marca.setText("");
        txt_Ano.setText("");
        txt_Cor.setText("");
        txt_ValorUnitario.setText("");

    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
        // TODO add your handling code here:

        String clienteJuridico = PessoaJuridicaController.consultarPorCNPJString(Long.parseLong(txt_ClientePf.getText()));
        
        if(clienteJuridico != null || clienteJuridico.equals("")){
            lbl_NomeClienteVenda.setText(clienteJuridico);
        }else {
            JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            txt_ClientePf.setText("");
        }
    }//GEN-LAST:event_btn_BuscarClienteActionPerformed

    private void btn_BuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarProdutoActionPerformed

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> listaProdutos = dao.consultaVendaProduto(txt_Produto.getText());

        if (listaProdutos != null) {
            for (Produto c : listaProdutos) {
                txt_IdProduto.setText(String.valueOf(c.getId()));
                txt_Modelo.setText(String.valueOf(c.getModelo()));
                txt_Marca.setText(String.valueOf(c.getMarca()));
                txt_Ano.setText(String.valueOf(c.getAno()));
                txt_Cor.setText(String.valueOf(c.getCor()));
                txt_Produto.setText(String.valueOf(c.getPlaca()));
                txt_ValorUnitario.setText(String.valueOf(c.getValorCompra()));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Produto não cadastrado");
            txt_Produto.setText("");
        }

        // LoadTableItemVenda(txt_Produto.getText());
    }//GEN-LAST:event_btn_BuscarProdutoActionPerformed

    private void txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MarcaActionPerformed

    private void txt_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AnoActionPerformed

    private void btn_RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoverActionPerformed
        DefaultTableModel venda = (DefaultTableModel) tbl_ItemVenda.getModel();
        if (tbl_ItemVenda.getSelectedRow() != -1) {
            venda.removeRow(tbl_ItemVenda.getSelectedRow());
            tbl_ItemVenda.setModel(venda);
        }
        Double valorT = 0.0;
        for (int i = 0; i < tbl_ItemVenda.getRowCount(); i++) {
            valorT = valorT + Double.parseDouble(tbl_ItemVenda.getValueAt(i, 6).toString());
        }
        lbl_valorTotalSet.setText("" + valorT);
    }//GEN-LAST:event_btn_RemoverActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        DefaultTableModel quantidadeProduto = (DefaultTableModel) tbl_ItemVenda.getModel();
        Object[] dados = {Integer.parseInt(txt_IdProduto.getText()), txt_Modelo.getText(), txt_Marca.getText(), txt_Ano.getText(),
            txt_Cor.getText(), txt_Produto.getText(), Double.parseDouble(txt_ValorUnitario.getText())};
        quantidadeProduto.addRow(dados);

        Double valorT = 0.0;
        for (int i = 0; i < tbl_ItemVenda.getRowCount(); i++) {
            valorT = valorT + Double.parseDouble(tbl_ItemVenda.getValueAt(i, 6).toString());
        }
        LimparFormulario();
        lbl_valorTotalSet.setText("" + valorT);
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaJuridica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_BuscarCliente;
    private javax.swing.JButton btn_BuscarProduto;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Remover;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_Cliente1;
    private javax.swing.JLabel lbl_ClientePfPj;
    private javax.swing.JLabel lbl_IdProduto;
    private javax.swing.JLabel lbl_NomeClienteVenda;
    private javax.swing.JLabel lbl_Produto;
    private javax.swing.JLabel lbl_TextoInfo;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_ValorUnitario;
    private javax.swing.JLabel lbl_valorTotal;
    private javax.swing.JLabel lbl_valorTotalSet;
    private javax.swing.JPanel pnl_TitlePageBackground;
    private javax.swing.JPanel pnl_TitleUserPageBackground;
    private javax.swing.JPanel pnl_VendaBackground;
    private javax.swing.JScrollPane scp_ItemVenda;
    private javax.swing.JTable tbl_ItemVenda;
    private javax.swing.JTextField txt_Ano;
    private javax.swing.JTextField txt_ClientePf;
    private javax.swing.JTextField txt_Cor;
    private javax.swing.JTextField txt_IdProduto;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_Modelo;
    private javax.swing.JTextField txt_Produto;
    private javax.swing.JTextField txt_ValorUnitario;
    // End of variables declaration//GEN-END:variables

}
