/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.view;

import br.senac.controller.PessoaFisicaController;
import br.senac.controller.ProdutoController;
import br.senac.model.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laay.dias
 */
public class Venda extends javax.swing.JFrame {

    public Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TitlePageBackground = new javax.swing.JPanel();
        pnl_UserBackground = new javax.swing.JPanel();
        lbl_TextoInfo = new javax.swing.JLabel();
        lbl_dataVenda = new javax.swing.JLabel();
        lbl_valorTotal = new javax.swing.JLabel();
        txt_valorTotal = new javax.swing.JTextField();
        lbl_TextoInfo2 = new javax.swing.JLabel();
        txt_dataVenda = new javax.swing.JTextField();
        txt_Pedido = new javax.swing.JTextField();
        txt_ClientePf = new javax.swing.JTextField();
        txt_Produto = new javax.swing.JTextField();
        lbl_ClientePfPj = new javax.swing.JLabel();
        lbl_Pedido = new javax.swing.JLabel();
        lbl_Produto = new javax.swing.JLabel();
        btn_BuscarCliente = new javax.swing.JButton();
        lbl_Cliente1 = new javax.swing.JLabel();
        lbl_NomeClienteVenda = new javax.swing.JLabel();
        btn_Adicionar = new javax.swing.JButton();
        lbl_ValorUnitario = new javax.swing.JLabel();
        txt_ValorUnitario = new javax.swing.JTextField();
        scp_ItemVenda = new javax.swing.JScrollPane();
        tbl_ItemVenda = new javax.swing.JTable();
        btn_Salvar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        pnl_TitleUserPageBackground = new javax.swing.JPanel();
        lbl_TitleLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_TitlePageBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnl_UserBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_UserBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        lbl_TextoInfo.setText("Preencha os campos abaixo:");

        lbl_dataVenda.setText("Data venda");

        lbl_valorTotal.setText("Valor total");

        lbl_TextoInfo2.setText("Todos os campos com \"*\" são obrigatórios!");

        lbl_ClientePfPj.setText("Cpf");

        lbl_Pedido.setText("Pedido");

        lbl_Produto.setText("Placa");

        btn_BuscarCliente.setText("Buscar");
        btn_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarClienteActionPerformed(evt);
            }
        });

        lbl_Cliente1.setText("Cliente:");

        lbl_NomeClienteVenda.setText("Label que vai aparece nomer do cliente");

        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        lbl_ValorUnitario.setText("Valor Unit");

        tbl_ItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Ano", "Cor", "Placa", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scp_ItemVenda.setViewportView(tbl_ItemVenda);

        javax.swing.GroupLayout pnl_UserBackgroundLayout = new javax.swing.GroupLayout(pnl_UserBackground);
        pnl_UserBackground.setLayout(pnl_UserBackgroundLayout);
        pnl_UserBackgroundLayout.setHorizontalGroup(
            pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TextoInfo)
                            .addComponent(lbl_TextoInfo2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_valorTotal)
                                    .addComponent(lbl_dataVenda))
                                .addGap(10, 10, 10)
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_dataVenda, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_valorTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addComponent(lbl_Cliente1)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_NomeClienteVenda))
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ClientePfPj)
                                    .addComponent(lbl_Produto)
                                    .addComponent(lbl_ValorUnitario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                        .addComponent(txt_ClientePf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_BuscarCliente))
                                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_ValorUnitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(txt_Produto, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Adicionar)))))
                        .addGap(49, 49, 49)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addComponent(lbl_Pedido)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                                .addComponent(scp_ItemVenda)
                                .addContainerGap())))))
        );
        pnl_UserBackgroundLayout.setVerticalGroup(
            pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_TextoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addComponent(lbl_TextoInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ClientePfPj)
                            .addComponent(txt_ClientePf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_BuscarCliente))
                        .addGap(7, 7, 7)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cliente1)
                            .addComponent(lbl_NomeClienteVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Produto)
                            .addComponent(txt_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Adicionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ValorUnitario)
                            .addComponent(txt_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valorTotal)))
                    .addGroup(pnl_UserBackgroundLayout.createSequentialGroup()
                        .addComponent(scp_ItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_UserBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataVenda)
                    .addComponent(txt_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Pedido))
                .addGap(61, 61, 61))
        );

        btn_Salvar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Salvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Limpar.setBackground(new java.awt.Color(71, 140, 104));
        btn_Limpar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TitlePageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitlePageBackground);
        pnl_TitlePageBackground.setLayout(pnl_TitlePageBackgroundLayout);
        pnl_TitlePageBackgroundLayout.setHorizontalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TitlePageBackgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(pnl_UserBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_TitlePageBackgroundLayout.setVerticalGroup(
            pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitlePageBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_UserBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_TitlePageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_TitleUserPageBackground.setBackground(new java.awt.Color(0, 99, 149));

        lbl_TitleLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setFont(new java.awt.Font("Century Gothic", 1, 56)); // NOI18N
        lbl_TitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleLoginPage.setText("Pole Position Store");

        javax.swing.GroupLayout pnl_TitleUserPageBackgroundLayout = new javax.swing.GroupLayout(pnl_TitleUserPageBackground);
        pnl_TitleUserPageBackground.setLayout(pnl_TitleUserPageBackgroundLayout);
        pnl_TitleUserPageBackgroundLayout.setHorizontalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TitleUserPageBackgroundLayout.setVerticalGroup(
            pnl_TitleUserPageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleUserPageBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_TitleLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_TitleUserPageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TitlePageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LoadTableItemVenda(String placa) {
        
        ArrayList<String[]> lista = ProdutoController.consultaPorPlaca(txt_Produto.getText());
        DefaultTableModel tmProduto = new DefaultTableModel();
        tmProduto.addColumn("ID");
        tmProduto.addColumn("Modelo");
        tmProduto.addColumn("Marca");
        tmProduto.addColumn("Ano");
        tmProduto.addColumn("Cor");
        tmProduto.addColumn("Placa");
        tmProduto.addColumn("Valor");
        tbl_ItemVenda.setModel(tmProduto);
        for (String[] c : lista) {
            tmProduto.addRow(c);
        }
        tbl_ItemVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_ItemVenda.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbl_ItemVenda.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(5).setPreferredWidth(50);
        tbl_ItemVenda.getColumnModel().getColumn(6).setPreferredWidth(50);
    }
    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // VendaController control = new VendaController();
        String valorTotal = txt_valorTotal.getText();
        /*String dataVenda = txt_dataVenda.getText();*/
        String cliente = txt_ClientePf.getText();
        String pedido = txt_Pedido.getText();
        String produto = txt_Produto.getText();

        if (valorTotal.equals("") || cliente.equals("") || pedido.equals("") || produto.equals("")) {;

            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            // control.salvar(Double.parseDouble(valorTotal), /*Date.valueOf(dataVenda),*/ cliente, pedido, produto);
            JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!");
            HomePage home = new HomePage();
            home.setVisible(true);
            Venda.this.dispose();
        }

    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        int logout = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Cancelar?");
        System.out.println(logout);
        if (logout == 0) {
            JOptionPane.showMessageDialog(rootPane, "Operação Cancelada!");
            HomePage home = new HomePage();
            home.setVisible(true);
            Venda.this.dispose();
        }
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        txt_valorTotal.setText("");
        txt_dataVenda.setText("");
        txt_ClientePf.setText("");
        txt_Pedido.setText("");
        txt_Produto.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
        // TODO add your handling code here:

        String cliente = PessoaFisicaController.consultaClienteVenda(Long.parseLong(txt_ClientePf.getText()));

        if (cliente != null) {
            lbl_NomeClienteVenda.setText(cliente);
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            txt_ClientePf.setText("");
        }
    }//GEN-LAST:event_btn_BuscarClienteActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        // TODO add your handling code here:
        /*List<Produto> lista = ProdutoController.consultarPorPlaca(txt_Produto.getText());
        
        DefaultTableModel quantidadeProduto = (DefaultTableModel) tbl_ItemVenda.getModel();
        Object[] dados = {Integer.parseInt(txt_IdItensVenda.getText()), Integer.parseInt(txt_QuantidadeItemVenda.getText()), Double.parseDouble(txt_ValorUnitarioVendas.getText())};
        quantidadeProduto.addRow(dados);*/
        
        LoadTableItemVenda(txt_Produto.getText());
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_BuscarCliente;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel lbl_Cliente1;
    private javax.swing.JLabel lbl_ClientePfPj;
    private javax.swing.JLabel lbl_NomeClienteVenda;
    private javax.swing.JLabel lbl_Pedido;
    private javax.swing.JLabel lbl_Produto;
    private javax.swing.JLabel lbl_TextoInfo;
    private javax.swing.JLabel lbl_TextoInfo2;
    private javax.swing.JLabel lbl_TitleLoginPage;
    private javax.swing.JLabel lbl_ValorUnitario;
    private javax.swing.JLabel lbl_dataVenda;
    private javax.swing.JLabel lbl_valorTotal;
    private javax.swing.JPanel pnl_TitlePageBackground;
    private javax.swing.JPanel pnl_TitleUserPageBackground;
    private javax.swing.JPanel pnl_UserBackground;
    private javax.swing.JScrollPane scp_ItemVenda;
    private javax.swing.JTable tbl_ItemVenda;
    private javax.swing.JTextField txt_ClientePf;
    private javax.swing.JTextField txt_Pedido;
    private javax.swing.JTextField txt_Produto;
    private javax.swing.JTextField txt_ValorUnitario;
    private javax.swing.JTextField txt_dataVenda;
    private javax.swing.JTextField txt_valorTotal;
    // End of variables declaration//GEN-END:variables
}
